module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.14

replace github.com/mattn/go-ieproxy => github.com/mattn/go-ieproxy v0.0.1

require github.com/minio/minio v0.0.0-20230112020616-7bc95c47a322
