name: go

on:
  pull_request:

permissions:  
  contents: read

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        parallelism: [8]
        index: [0, 1, 2, 3, 4, 5, 6, 7]
    runs-on: ubuntu-24.04
    name: Thanos end-to-end tests
    env:
      GOBIN: /tmp/.bin
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install Go.
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: 1.26.x

      - uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
        with:
          path: |
            ~/.cache/go-build
            ~/.cache/golangci-lint
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run e2e docker-based tests
        run: make test-e2e-local GH_PARALLEL=${{ matrix.parallelism }} GH_INDEX=${{ matrix.index }}
